# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: Release

on:
  push:
    tags:
      - "*" # Push events to matching v*, i.e. v1.0, v20.15.10
permissions:
  contents: write
env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-24.04]

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt install libopencv-dev libpam0g-dev libcli11-dev
          mkdir -p external && cd external
          wget -O libtorch.zip https://download.pytorch.org/libtorch/nightly/cpu/libtorch-cxx11-abi-shared-without-deps-2.2.0.dev20231031%2Bcpu.zip
          unzip libtorch.zip

      - name: Configure CMake
        env:
          PROJECT_VERSION: ${{github.ref_name}}
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{env.BUILD_TYPE}}

      - name: Package
        working-directory: ${{github.workspace}}/build
        run: |
          cpack
          mv facepass-${{ github.ref_name }}-Linux.deb facepass-${{ github.ref_name }}-${{ matrix.os }}.deb

      
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ${{github.workspace}}/build/facepass-*.deb
          token: ${{secrets.GITHUB_TOKEN}}
          tag_name: ${{github.ref_name}}
          name: ${{github.ref_name}}
